### ISSUE TITLE
# ✨ DevOps Task: Redeploy Latest Backend for Distributed Sessions

### ISSUE THREAD

**Issue by joepegler** [bcnmy/sdk#104]
## What

Redeploy the latest version of the Distributed Sessions backend, updating the wallet-provider-service-sdk dependency and configuring the environment variables.

## Why

- Ensure the backend is running the most up-to-date version of the wallet-provider-service-sdk
- Apply the latest configurations and environment settings
- Maintain consistency between the backend and the frontend demo
- Improve overall system stability and performance

## How

1. Update the `Cargo.toml` file in the `dan-demo-backend` repository:
   ```toml
   [dependencies.wallet-provider-service-sdk]
   version = "0.2.0"
   ```

2. Create or update the `.env` file with the following contents:
   ```
   LISTEN="0.0.0.0:8090"
   AGGREGATOR="ws://check-with-chirag"
   TOKEN="test-token"
   ```

3. Pull the latest changes from the `dan-demo-backend` repository:
   ```
   git pull origin main
   ```

4. Build the updated backend:
   ```
   cargo build --release
   ```

5. Stop the currently running backend service

6. Start the new backend service with the updated environment variables:
   ```
   source .env && ./target/release/dan-demo-backend
   ```

7. Verify the backend is running correctly:
   - Check logs for any startup errors
   - Perform a basic health check (e.g., ping the service)

8. Update any necessary documentation or deployment scripts to reflect the changes

9. If using a container-based deployment:
   - Update the Dockerfile to use the new wallet-provider-service-sdk version
   - Rebuild the container image
   - Deploy the new container to the production environment

10. Perform a smoke test to ensure the frontend demo works correctly with the updated backend

## References

- [dan-demo-backend Repository](https://github.com/bcnmy/dan-demo-backend)
- [wallet-provider-service-sdk Repository](https://github.com/silence-laboratories/walletprovider-sdk)
- [WPFE Demo + SDK Example](https://github.com/silence-laboratories/walletprovider-sdk/blob/43bee6454c74c29db15d07a63c09bf67254cebc4/demo/src/routes/%2Bpage.svelte)

**Comment by Graeme-Code** [comment]
@TakGN I made this a High priority purely because its blocking completion of the task and its required for Devcon. could you aim to complete this before Joe gets back from leave?

**Comment by TakGN** [comment]
Update finished, devs can test.

**Comment by livingrockrises** [comment]
I have tested and it seems to be working fine.

if url changes or package version bump is release from the side of silence labs, then we will follow the same process.
