### ISSUE TITLE
feat: distributed session keys

### ISSUE THREAD

**Issue by joepegler** [bcnmy/sdk#63]
## What

- Implement support for distributed session keys in the Biconomy Client SDK

## Why

"Implementing distributed session keys will enhance the security and flexibility of our SDK. This feature will allow for more granular control over permissions and improve the overall user experience. Expected outcomes include:
- Improved security through distributed key management
- Enhanced flexibility for developers implementing session-based authentication
- Better alignment with emerging standards in account abstraction"

## How

      1. Adding a new `DANSessionKeyManagerModule` to handle distributed session keys
      2. Updating the `sessions` module to include support for distributed session key functionality
      3. Modifying the `Account` to integrate the new session key features
      4. Updating relevant types and utility functions to accommodate the new distributed session key structure
      5. Adjusting test suites to cover the new functionality
      6. Updating documentation to reflect the new features and usage"

**Comment by joepegler** [comment]
SL are now ready with epv7

**Comment by livingrockrises** [comment]
in your branch I could not find the methods like authenticateAndSign and authenticateAndCreateKey so I wonder how much is done. @joepegler

**Comment by livingrockrises** [comment]
backend is deployed. where do you need to configure that url?
and how come tests are passing (if they include dan files)

**Comment by joepegler** [comment]
I probably just didnt push. Will check in the morning

**Comment by livingrockrises** [comment]
let me know when you push @joepegler
