### ISSUE TITLE
# ✨ Feature Request: Integrate 'trustAttesters' Call into Smart Sessions Module

### ISSUE THREAD

**Issue by joepegler** [bcnmy/sdk#99]
### Feature or Improvement Description

Integrate the 'trustAttesters' call into the `grantPermission` decorator and create a new 'requiresTrustAttesters' decorator to optimize the permission granting process in the Smart Sessions Module.

### Benefits & Outcomes

- Streamline the process of granting permissions by automatically handling the 'trustAttesters' call
- Reduce the number of separate transactions users need to make
- Improve user experience by simplifying the permission granting flow
- Ensure that necessary attesters are trusted before permissions are granted
- Optimize gas usage by combining operations where possible

### Implementation Ideas

1. Create a new 'requiresTrustAttesters' decorator:
   - This decorator should check if attesters need to be trusted
   - If trust is needed, prepare the trustAttesters call for later use

2. Modify the `grantPermission` decorator:
   - Incorporate the 'trustAttesters' call if it's required
   - Combine the 'trustAttesters' and 'grantPermission' calls into a single userOp when necessary

3. Update the Smart Sessions Module to use these new decorators:
   - Apply both decorators to relevant methods, such as createSession

4. Implement helper functions:
   - Function to check if attesters need trust
   - Function to prepare the trustAttesters call
   - Function to retrieve the prepared trustAttesters call

5. Update the `toSmartSessionsValidator` function to incorporate the new decorators and logic

6. Modify the smart contract:
   - Handle the combined 'trustAttesters' and 'grantPermission' calls efficiently

7. Update unit and integration tests to cover the new combined flow

8. Update documentation to reflect the new automatic 'trustAttesters' functionality

9. Optimize gas usage for the combined calls

10. Implement proper error handling for cases where 'trustAttesters' fails but 'grantPermission' would have succeeded

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct.

**Comment by livingrockrises** [comment]
Noting here> Attestation can be checked this way

cast call 0x000000000069E2a187AEFFb852bF3cCdC95151B2 "findAttestation(address,address)" 0xDDFF43A42726df11E34123f747bDce0f755F784d 0xA4C777199658a41688E9488c4EcbD7a2925Cc23A --rpc-url https://sepolia.base.org/

0x00000000000000000000000000000000000000000000000000000000670d78da000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000ddff43a42726df11e34123f747bdce0f755f784d000000000000000000000000a4c777199658a41688e9488c4ecbd7a2925cc23a0000000000000000000000007924f0cbbc7ec866c557dce7fd262fc6c367e73393d46fcca4ef7d66a413c7bde08bb1ff14bacbd04c4069bb24cd7c21729d7bf1

or answer is 

0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

if no attestations done

**Comment by livingrockrises** [comment]
^ this gives if a particular module has been attested and weather we need to make trustAttesters call

**Comment by livingrockrises** [comment]
This function call on registry gives you trusted attesters for smart account.

function findTrustedAttesters(address smartAccount) public view returns (address[] memory attesters) {
...
}
